package app.resource.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.live.fox.entity.MountResourceBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOUNT_RESOURCE_BEAN".
*/
public class MountResourceBeanDao extends AbstractDao<MountResourceBean, Long> {

    public static final String TABLENAME = "MOUNT_RESOURCE_BEAN";

    /**
     * Properties of entity MountResourceBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Ename = new Property(2, String.class, "ename", false, "ENAME");
        public final static Property Gshort = new Property(3, String.class, "gshort", false, "GSHORT");
        public final static Property Type = new Property(4, int.class, "type", false, "TYPE");
        public final static Property Price = new Property(5, int.class, "price", false, "PRICE");
        public final static Property LogUrl = new Property(6, String.class, "logUrl", false, "LOG_URL");
        public final static Property AnimationUrl = new Property(7, String.class, "animationUrl", false, "ANIMATION_URL");
        public final static Property AnimationTime = new Property(8, int.class, "animationTime", false, "ANIMATION_TIME");
        public final static Property Compress = new Property(9, int.class, "compress", false, "COMPRESS");
        public final static Property Status = new Property(10, int.class, "status", false, "STATUS");
        public final static Property Sort = new Property(11, int.class, "sort", false, "SORT");
        public final static Property ShowFront = new Property(12, int.class, "showFront", false, "SHOW_FRONT");
        public final static Property Descript = new Property(13, String.class, "descript", false, "DESCRIPT");
        public final static Property CreateTime = new Property(14, Long.class, "createTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(15, Long.class, "updateTime", false, "UPDATE_TIME");
        public final static Property LocalShouldUpdate = new Property(16, int.class, "localShouldUpdate", false, "LOCAL_SHOULD_UPDATE");
        public final static Property LocalImgPath = new Property(17, String.class, "localImgPath", false, "LOCAL_IMG_PATH");
        public final static Property LocalSvgPath = new Property(18, String.class, "localSvgPath", false, "LOCAL_SVG_PATH");
    }


    public MountResourceBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MountResourceBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOUNT_RESOURCE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"ENAME\" TEXT," + // 2: ename
                "\"GSHORT\" TEXT," + // 3: gshort
                "\"TYPE\" INTEGER NOT NULL ," + // 4: type
                "\"PRICE\" INTEGER NOT NULL ," + // 5: price
                "\"LOG_URL\" TEXT," + // 6: logUrl
                "\"ANIMATION_URL\" TEXT," + // 7: animationUrl
                "\"ANIMATION_TIME\" INTEGER NOT NULL ," + // 8: animationTime
                "\"COMPRESS\" INTEGER NOT NULL ," + // 9: compress
                "\"STATUS\" INTEGER NOT NULL ," + // 10: status
                "\"SORT\" INTEGER NOT NULL ," + // 11: sort
                "\"SHOW_FRONT\" INTEGER NOT NULL ," + // 12: showFront
                "\"DESCRIPT\" TEXT," + // 13: descript
                "\"CREATE_TIME\" INTEGER," + // 14: createTime
                "\"UPDATE_TIME\" INTEGER," + // 15: updateTime
                "\"LOCAL_SHOULD_UPDATE\" INTEGER NOT NULL ," + // 16: localShouldUpdate
                "\"LOCAL_IMG_PATH\" TEXT," + // 17: localImgPath
                "\"LOCAL_SVG_PATH\" TEXT);"); // 18: localSvgPath
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOUNT_RESOURCE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MountResourceBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String ename = entity.getEname();
        if (ename != null) {
            stmt.bindString(3, ename);
        }
 
        String gshort = entity.getGshort();
        if (gshort != null) {
            stmt.bindString(4, gshort);
        }
        stmt.bindLong(5, entity.getType());
        stmt.bindLong(6, entity.getPrice());
 
        String logUrl = entity.getLogUrl();
        if (logUrl != null) {
            stmt.bindString(7, logUrl);
        }
 
        String animationUrl = entity.getAnimationUrl();
        if (animationUrl != null) {
            stmt.bindString(8, animationUrl);
        }
        stmt.bindLong(9, entity.getAnimationTime());
        stmt.bindLong(10, entity.getCompress());
        stmt.bindLong(11, entity.getStatus());
        stmt.bindLong(12, entity.getSort());
        stmt.bindLong(13, entity.getShowFront());
 
        String descript = entity.getDescript();
        if (descript != null) {
            stmt.bindString(14, descript);
        }
 
        Long createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(15, createTime);
        }
 
        Long updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(16, updateTime);
        }
        stmt.bindLong(17, entity.getLocalShouldUpdate());
 
        String localImgPath = entity.getLocalImgPath();
        if (localImgPath != null) {
            stmt.bindString(18, localImgPath);
        }
 
        String localSvgPath = entity.getLocalSvgPath();
        if (localSvgPath != null) {
            stmt.bindString(19, localSvgPath);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MountResourceBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String ename = entity.getEname();
        if (ename != null) {
            stmt.bindString(3, ename);
        }
 
        String gshort = entity.getGshort();
        if (gshort != null) {
            stmt.bindString(4, gshort);
        }
        stmt.bindLong(5, entity.getType());
        stmt.bindLong(6, entity.getPrice());
 
        String logUrl = entity.getLogUrl();
        if (logUrl != null) {
            stmt.bindString(7, logUrl);
        }
 
        String animationUrl = entity.getAnimationUrl();
        if (animationUrl != null) {
            stmt.bindString(8, animationUrl);
        }
        stmt.bindLong(9, entity.getAnimationTime());
        stmt.bindLong(10, entity.getCompress());
        stmt.bindLong(11, entity.getStatus());
        stmt.bindLong(12, entity.getSort());
        stmt.bindLong(13, entity.getShowFront());
 
        String descript = entity.getDescript();
        if (descript != null) {
            stmt.bindString(14, descript);
        }
 
        Long createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(15, createTime);
        }
 
        Long updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindLong(16, updateTime);
        }
        stmt.bindLong(17, entity.getLocalShouldUpdate());
 
        String localImgPath = entity.getLocalImgPath();
        if (localImgPath != null) {
            stmt.bindString(18, localImgPath);
        }
 
        String localSvgPath = entity.getLocalSvgPath();
        if (localSvgPath != null) {
            stmt.bindString(19, localSvgPath);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MountResourceBean readEntity(Cursor cursor, int offset) {
        MountResourceBean entity = new MountResourceBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ename
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // gshort
            cursor.getInt(offset + 4), // type
            cursor.getInt(offset + 5), // price
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // logUrl
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // animationUrl
            cursor.getInt(offset + 8), // animationTime
            cursor.getInt(offset + 9), // compress
            cursor.getInt(offset + 10), // status
            cursor.getInt(offset + 11), // sort
            cursor.getInt(offset + 12), // showFront
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // descript
            cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14), // createTime
            cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15), // updateTime
            cursor.getInt(offset + 16), // localShouldUpdate
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // localImgPath
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18) // localSvgPath
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MountResourceBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGshort(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setType(cursor.getInt(offset + 4));
        entity.setPrice(cursor.getInt(offset + 5));
        entity.setLogUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAnimationUrl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAnimationTime(cursor.getInt(offset + 8));
        entity.setCompress(cursor.getInt(offset + 9));
        entity.setStatus(cursor.getInt(offset + 10));
        entity.setSort(cursor.getInt(offset + 11));
        entity.setShowFront(cursor.getInt(offset + 12));
        entity.setDescript(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCreateTime(cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14));
        entity.setUpdateTime(cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15));
        entity.setLocalShouldUpdate(cursor.getInt(offset + 16));
        entity.setLocalImgPath(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setLocalSvgPath(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MountResourceBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MountResourceBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MountResourceBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
