package app.resource.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.live.fox.entity.UserVehiclePlayLimitBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_VEHICLE_PLAY_LIMIT_BEAN".
*/
public class UserVehiclePlayLimitBeanDao extends AbstractDao<UserVehiclePlayLimitBean, Long> {

    public static final String TABLENAME = "USER_VEHICLE_PLAY_LIMIT_BEAN";

    /**
     * Properties of entity UserVehiclePlayLimitBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uid = new Property(1, String.class, "uid", false, "UID");
        public final static Property LiveId = new Property(2, String.class, "liveId", false, "LIVE_ID");
        public final static Property ShowTime = new Property(3, long.class, "showTime", false, "SHOW_TIME");
        public final static Property Type = new Property(4, int.class, "type", false, "TYPE");
    }


    public UserVehiclePlayLimitBeanDao(DaoConfig config) {
        super(config);
    }
    
    public UserVehiclePlayLimitBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_VEHICLE_PLAY_LIMIT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UID\" TEXT," + // 1: uid
                "\"LIVE_ID\" TEXT," + // 2: liveId
                "\"SHOW_TIME\" INTEGER NOT NULL ," + // 3: showTime
                "\"TYPE\" INTEGER NOT NULL );"); // 4: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_VEHICLE_PLAY_LIMIT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserVehiclePlayLimitBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(2, uid);
        }
 
        String liveId = entity.getLiveId();
        if (liveId != null) {
            stmt.bindString(3, liveId);
        }
        stmt.bindLong(4, entity.getShowTime());
        stmt.bindLong(5, entity.getType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserVehiclePlayLimitBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(2, uid);
        }
 
        String liveId = entity.getLiveId();
        if (liveId != null) {
            stmt.bindString(3, liveId);
        }
        stmt.bindLong(4, entity.getShowTime());
        stmt.bindLong(5, entity.getType());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserVehiclePlayLimitBean readEntity(Cursor cursor, int offset) {
        UserVehiclePlayLimitBean entity = new UserVehiclePlayLimitBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // liveId
            cursor.getLong(offset + 3), // showTime
            cursor.getInt(offset + 4) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserVehiclePlayLimitBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLiveId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setShowTime(cursor.getLong(offset + 3));
        entity.setType(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserVehiclePlayLimitBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserVehiclePlayLimitBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserVehiclePlayLimitBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
